# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4dcba738a5aa13f8b92c76d76c8efbf25c34f6b4f78a3932b2d8880054eb19d7500944be4b68942a03b56dee4d1451316689a2f715aec166ce96bca9d6f19c7e

test:
  secret_key_base: 84f06ef9d4a4afa536a5660dbb8f26e17e4d43c4ffadd3c8dc67457d231aec47a617e8edb86bd8d0ebb221bda3ad98177583aa4480946adceb1ac4d3df419901

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
